DAYS_PER_YEAR = 365.25

TRADE_TYPE_LONG = 'LONG'
TRADE_TYPE_SHORT = 'SHORT'

TRADE_ACTION_OPEN = 'OPEN'
TRADE_ACTION_CLOSE = 'CLOSE'

ORDER_TYPE_BUY = 'BUY'
ORDER_TYPE_SELL = 'SELL'

# Database table names
TABLE_STRATEGY_RUNS = 'strategy_runs'
TABLE_STRATEGY_PRESETS = 'strategy_presets'
TABLE_OHLCV_DATA = 'ohlcv_data'
TABLE_DATA_METADATA = 'data_metadata'
